### ISSUE TITLE
Kupid patches out `minDomains` from TopologySpreadConstraints

### ISSUE THREAD

**Issue by timuthy** [gardener/kupid#72]
**What happened**:
Gardener sets `topologySpreadConstraints[].minDomains` (added in Kubernetes 1.24) in StatefulSets and Deployments. With Kupid modifying affected resources, the field is removed again.

**What you expected to happen**:
`minDomains` to remain in the `podTemplate` specification.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy and configure Kupid to modify a `Deployment`, and set topologySpreadConstraints[].minDomains`.

**Anything else we need to know**:
Kupid's sources are based on `k8s.io/api v0.23.3` which does not include this field. This is possibly the root cause of the problem, i.e. the patch is not calculated properly.

**Comment by unmarshall** [comment]
Nice catch @timuthy
@shreyas-s-rao lets take this opportunity to update go mod dependencies - many of them are now ancient.
